version: "2.2"

services:
  kafka: # https://debezium.io/documentation/reference/2.2/tutorial.html#starting-kafka
    image: debezium/kafka:2.3.1.Final
    container_name: kafka
    hostname: kafka
    platform: "linux/amd64"
    environment:
      BROKER_ID: 1
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - zookeeper
  zookeeper: # https://debezium.io/documentation/reference/2.2/tutorial.html#starting-zookeeper
    image: debezium/zookeeper:2.3.1.Final
    container_name: zookeeper
    hostname: zookeeper
    platform: "linux/amd64"
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      DYNAMIC_CONFIG_ENABLED: "true"
